### ISSUE TITLE
option to sync to mega.nz cloud

### ISSUE THREAD

**Issue by KraXen72** [stingle/stingle-photos-android#110]
please add an option to connect your mega.nz account and sync there. it would be great. 
mega has opensource all of its apps, even android ones and has sdks that can be used.
please take a look.
thank you.

**Comment by alexamiryan** [comment]
Hello. Sorry but this is not something we will consider implementing, as it's conflicts with the Stingle's business model. We are promoting our own cloud and this is the only source of the Stingle's income.

**Comment by KraXen72** [comment]
okay
