### ISSUE TITLE
Cant open app with fingerprint disabled

### ISSUE THREAD

**Issue by Kreuger** [stingle/stingle-photos-android#115]
Hey guys. Ive been having issues on my phone with the fingerprint reader so I have disabled it and now Stingle closes immediately which I assume is because I set it up to unlock that way. Is there any way I can change it without losing my photos and no cloud sync?

**Comment by alexamiryan** [comment]
Can you explain when it crashes? On app open? Can you do a logout?
Please note that if you clear app data you will loose all photos and videos the are not backed up yet

**Comment by Kreuger** [comment]
It started working again at some point. And Ive since readded my fingerprint so we can close this.
