### ISSUE TITLE
No SECURITY.md file

### ISSUE THREAD

**Issue by samuel-lucas6** [stingle/stingle-photos-android#117]
I recommend adding a [SECURITY.md](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) file for both [this](https://github.com/stingle/stingle-photos-android/security) repo and the [iOS](https://github.com/stingle/stingle-photos-ios/security) repo to clarify how to report vulnerabilities. This could then be linked on the [Security](https://stingle.org/security/) page of the website. 

Also, since you're currently hiring, does that mean you could afford to have a bug bounty program? If so, then that's a good way of encouraging people to look at the code.

**Comment by alexamiryan** [comment]
Thank for the suggestion Samuel. Will include SECURITY.md file with the next release.
Unfortunately we can't afford to have a bug bounty program right now.
