### ISSUE TITLE
Crash on Register / Login

### ISSUE THREAD

**Issue by n00b42** [stingle/stingle-photos-android#140]
First Test (Register):
- App fresh install
- Register (then autologin)
- Crash
- App Restart => crash

Second Test (Login)
- App fresh install
- Login (as account was created successful)
- Crash
- App Restart => crash

More info:
- Enabling fingerprint login has no influence (crash after fingerprint accepted)
- Connecting to a official or custom server also does not make a difference.

Device:
- Google Nexus 5
- Android 13

**Comment by alexamiryan** [comment]
Thanks for the report. Already know about this issue. Will be fixed today and pushed as an update , tomorrow.

**Comment by n00b42** [comment]
ok, thanks, so no logcat required?

**Comment by alexamiryan** [comment]
No. Update is out already, waiting for Google and F-Droid to release them


------- Original Message -------

**Comment by n00b42** [comment]
Just got the update to 2.10.2 (Google Playstore)
Issue seems to be resolved, also I did not encounter other problems in my short test.
Thank you!

**Comment by alexamiryan** [comment]
Thanks a lot! Sorry for the inconvenience.
