### ISSUE TITLE
Implement F-Droid's Gitlab compilation and post app to F-Droid

### ISSUE THREAD

**Issue by alexamiryan** [stingle/stingle-photos-android#16]
F-Droid link: https://gitlab.com/fdroid/rfp/-/issues/1191

**Comment by alexamiryan** [comment]
Possible solution: https://github.com/terl/lazysodium-android/issues/38#issuecomment-718077553

**Comment by IzzySoft** [comment]
As Stingle is listed at F-Droid now: shall I still keep it in my repo? I usually remove it after a decent overlap, which would be in about 10d from now (see [here for some background](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ)).

**Comment by alexamiryan** [comment]
As updates are faster for IzzyOnDroid, maybe it is reasonable to keep it in both repos? For example in case that we have a critical issue and need to fix it ASAP?

**Comment by IzzySoft** [comment]
That is true – but as the signatures don't match will only help those having installed the app from my repo (or from Play, or from Github).

**Comment by alexamiryan** [comment]
That's true. So let's remove it from IzzyOnDroid then

**Comment by IzzySoft** [comment]
OK, marking it for removal then. Should you need it back any time later for whatever reason, just let me know; wouldn't be the first app being revived here :smile: Thanks!

**Comment by alexamiryan** [comment]
Thanks a lot!
