### ISSUE TITLE
Does it rely on Google Services?

### ISSUE THREAD

**Issue by dm17** [stingle/stingle-photos-android#41]
For those without the Google Play store: does your app depend on google services on Android? Are there any plans to get it into F-DROID?
Thanks :)

**Comment by alexamiryan** [comment]
Hello, 
Stingle Photos does not depend on Google Services except for billing. It uses Google Pay as a payment method. We have plans on implementing some other third party billing for those without Google services.
Yes we have plans to go to F-Droid, however we need to implement Libsodium compilation from sources for F-Droid's Gitlab CI/CD.
