### ISSUE TITLE
per-release changelogs

### ISSUE THREAD

**Issue by IzzySoft** [stingle/stingle-photos-android#78]
Looks like you forgot to put the `<versionCode>.txt` files into Fastlane's `changelogs/` folder for a while. If it's an oversight, count this as "friendly heads-up" :smile: Else just let me know, so I don't bother you again with this :rofl: Thanks!

**Comment by alexamiryan** [comment]
Hello Izzy,
Yes, I just forgot to do that. Will push an update with all the missing changelogs.
Will make sure that this doesn't happen again :)

**Comment by IzzySoft** [comment]
Thanks!

**Comment by alexamiryan** [comment]
Done

**Comment by IzzySoft** [comment]
Thanks, worked perfectly! Will show up with the next sync in about 16h from now.
