### ISSUE TITLE
stingle makes files broken: the most of my photos and videos are cut off to 1MB size and part of images are grey

### ISSUE THREAD

**Issue by AIGeneratedUsername** [stingle/stingle-photos-android#90]
The most of my photos are now exactly 1 MB at size and look cut off partially.

Photos are broken. Part of each photo now just grey. All broken photos has exactly 1 MB size.

Broken photo example (not broken part of a photo is blurred due to privacy reasons): 

![my_photo_blured](https://user-images.githubusercontent.com/70140627/123510432-09d91b00-d66b-11eb-9f51-808145520175.jpg)

UPD:

My videos are cut off to 1 MB size too.

**Comment by alexamiryan** [comment]
Unfortunately this was a bug that caused files to be partially imported. It's fixed 3 versions ago, however you need to import affected files again, because they are incomplete.
